"""20.05 Connections

Revision ID: 4d5f0df8f5dc
Revises: 
Create Date: 2020-05-20 22:15:17.464666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5f0df8f5dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_arr', sa.String(length=120), nullable=True),
    sa.Column('date_dep', sa.String(length=120), nullable=True),
    sa.Column('time_arr', sa.String(length=120), nullable=True),
    sa.Column('time_dep', sa.String(length=120), nullable=True),
    sa.Column('city_arr', sa.String(length=120), nullable=True),
    sa.Column('city_dep', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_city_arr'), 'train', ['city_arr'], unique=False)
    op.create_index(op.f('ix_train_city_dep'), 'train', ['city_dep'], unique=False)
    op.create_index(op.f('ix_train_date_arr'), 'train', ['date_arr'], unique=False)
    op.create_index(op.f('ix_train_date_dep'), 'train', ['date_dep'], unique=False)
    op.create_index(op.f('ix_train_time_arr'), 'train', ['time_arr'], unique=False)
    op.create_index(op.f('ix_train_time_dep'), 'train', ['time_dep'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['train.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_cost'), 'ticket', ['cost'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_cost'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_train_time_dep'), table_name='train')
    op.drop_index(op.f('ix_train_time_arr'), table_name='train')
    op.drop_index(op.f('ix_train_date_dep'), table_name='train')
    op.drop_index(op.f('ix_train_date_arr'), table_name='train')
    op.drop_index(op.f('ix_train_city_dep'), table_name='train')
    op.drop_index(op.f('ix_train_city_arr'), table_name='train')
    op.drop_table('train')
    # ### end Alembic commands ###
